from .user import User
from .institution import Institution
from .permission import Permission
from .role import Role
from .permission_role import PermissionRole
from .year import Year
from .institutions_group import InstitutionsGroup
from .year_goal import YearlyGoal
from .action_way import ActionWay
from .milestone import Milestone
from .yearly_indice import YearlyIndice
from .indice_type import IndiceType
from .conclusion import Conclusion
from .expect import Expect
from .institution_details import InstitutionDetails
from .institutionprogram import InstitutionProgram
