# builder image
FROM node:14.1 as builder

RUN mkdir /usr/app
WORKDIR /usr/app

# add `/usr/app/node_modules/.bin` to $PATH
ENV PATH /usr/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY client/package.json /usr/app/package.json

RUN npm install
RUN npm install -g @angular/cli
RUN npm install --unsafe-perm

COPY client/ /usr/app

RUN export NG_CLI_ANALYTICS=ci

RUN ng build --prod

#nginx with client-angular
FROM  nginx:1.13.9-alpine

COPY --from=builder /usr/app/dist /var/www/html/akiva

EXPOSE 80