FROM node:14.15.0

RUN mkdir /usr/app
WORKDIR /usr/app

# add `/usr/app/node_modules/.bin` to $PATH
ENV PATH /usr/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY client/package.json /usr/app/package.json

#RUN npm install --legacy-peer-deps

RUN npm install -g @angular/cli

RUN npm i

#RUN export NG_CLI_ANALYTICS=ci
CMD [ "npm", "run","start" ] 

EXPOSE 80